class AbortError(Exception): ...
class ChunksOkError(AbortError): ...
class TilesOkError(AbortError): ...
class DecodeOkError(AbortError): ...
class GetTilesOkError(AbortError): ...
class HMDDatasetError(AbortError): ...
